# Generated by Django 3.2.3 on 2021-07-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cоздан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Oбновлён')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('СЗД', 'Создание'), ('ОПЛ', 'Оплачен'), ('ГКВ', 'Готов к выдаче'), ('ОБН', 'Обнволен'), ('ОТМ', 'Отменён'), ('ВЫД', 'Выдан')], default='СЗД', max_length=3, verbose_name='Cтатус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы заказов',
                'ordering': ['order'],
            },
        ),
    ]
