# Generated by Django 3.2.3 on 2021-08-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
